print("Введите длины сторон a, b, c треугольнка")   
print("Сторона a: ") 
a = float(input())
print("Сторона b: ") 
b = float(input())
print("Сторона c: ") 
c = float(input())

print("Площадь треугольника равена:", a * b / 2) 
print("Периметр треугольника равен:", a + b + c) 
